Pizza project done
vladislav3112/making-pizzas-project-OOP pull request #1
Opened 2022-10-31 17:09 UTC by vladislav3112

Закончено задание pizza_project (Кодим 🍕.py)

2022-11-20 18:01 UTC, ffix requested changes
Спасибо за тесты и решение!
Из недостатков: всё в одном большом файле, хорошо бы разделить на несколько.
Очень сложные тесты с кучей логики внутри, тесты должны быть максимально простые.

2022-11-20 18:01 UTC, ffix commented on pizza_order.py
> +def order(pizza: Union[str, Pizza], delivery: bool, pickup: bool):
Сейчас флаги delivery и pickup можно выставить вместе, это странно. Нужно их сделать взаимоисключающими, click это умеет.

2022-11-20 18:01 UTC, ffix commented on pizza_order.py
> +def bake_(pizza: Pizza):
Несколько странный нейминг, в чём смысл `_` после названия функции?

2022-11-20 18:01 UTC, ffix commented on pizza_order.py
> +        "— Margherita 🧀 : tomato sauce, mozzarella, tomatoes\n— Pepperoni 🍕 : tomato sauce, mozzarella, pepperoni\n— Hawaiian 🍍 : tomato sauce, mozzarella, chicken, pineapples"
Длинные строчки стоит разбивать на несколько. Можно таким способом:
```
print(
    "some string\n"
    "a string continuation\n"
    "the last string"
)
```

2022-11-20 18:01 UTC, ffix commented on pizza_order.py
> +from time import sleep
Импорты некорректно отсоритрованы (не по pep8):
https://peps.python.org/pep-0008/#imports

2022-11-20 18:01 UTC, ffix commented on pizza_order.py
> +    return getattr(sys.modules[__name__], str.title())
Если ввести неправильное название пиццы, будет исключение, программа его не отлавливает.

2022-11-20 18:01 UTC, ffix commented on pizza_order.py
> +        name = type(self).__name__ + " " + self.emoji
Лучше не конкатенировать строки, а форматировать их через f-strings или format()

2022-11-20 18:01 UTC, ffix commented on test_pizza_order.py
> +    builtins.print = mock
Не стоит вручную подменять builtins или что-то другое, в pytest есть monlkeypatch: https://docs.pytest.org/en/latest/how-to/monkeypatch.html

2022-11-20 18:01 UTC, ffix commented on test_pizza_order.py
> +        with contextlib.redirect_stdout(str_io):
Для работы с stdin/stdout лучше использовать capsys: https://docs.pytest.org/en/latest/reference/reference.html#std-fixture-capsys

2022-11-20 18:01 UTC, ffix commented on test_pizza_order.py
> +def test_log_output(test_pizza_obj, test_func):
Очень много сложной логики в тестах, тесты должны максимально простые, иначе легко наделать багов в них. if-ов, как здесь, надо максимально избегать.

2022-12-03 17:54 UTC, vladislav3112 commented
Внёс требуемые изменения.

2022-12-03 17:57 UTC, vladislav3112 commented on pizza_order.py
> +def bake_(pizza: Pizza):
Первое, что пришло в голову, чтобы не совпало название функции с названием флага (delivery, например), но уже придумал название получше

2022-12-10 23:42 UTC, ffix commented
Спасибо за правки, но исправлены не все замечания

2022-12-12 11:40 UTC, vladislav3112 commented
Сортировку импортов и f-strings увидел и исправил, возможно что-то ещё не заметил. Если да, то можно узнать конкретнее что?

2023-05-08 10:16 UTC, merged